### ISSUE TITLE
UI does not work properly

### ISSUE THREAD

**Issue by ziyar-uzel** [rsverhagen94/TUD-Collaborative-AI-2023#3]
I have cloned the repo, created a virtual environment inside the folder, and installed the required libraries.
This is what I get, when I run `pip freeze` :
 `bidict==0.21.2
certifi==2022.12.7
cffi==1.15.1
chardet==4.0.0
charset-normalizer==3.0.1
click==8.1.3
colorama==0.4.6
colour==0.1.5
docutils==0.16
Flask==2.1.3
Flask-Cors==3.0.10
Flask-SocketIO==5.3.2
gevent==21.1.2
greenlet==1.0.0
idna==3.4
importlib-metadata==6.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
jsonpickle==1.5.1
MarkupSafe==2.1.2
matrx==2.2.0
numpy==1.20.0
pycparser==2.21
Pygments==2.14.0
python-engineio==4.3.4
python-socketio==5.7.2
requests==2.28.2
six==1.16.0
urllib3==1.26.14
Werkzeug==2.0.0
zipp==3.14.0
zope.event==4.6
zope.interface==5.5.2`

When I run the main.py I get these warnings:
C:\Users\iuzel\cai_proj\TUD-Collaborative-AI-2023\brains1\HumanBrain.py:20: UserWarning: FOV Occlusion is not yet fully implemented. Setting fov_occlusion to True has no effect.
  warnings.warn("FOV Occlusion is not yet fully implemented. "
C:\Users\iuzel\cai_proj\TUD-Collaborative-AI-2023\virt_env\lib\site-packages\matrx\world_builder.py:2403: UserWarning: A media folder path for the MATRX visualizer was given, but run_matrx_visualizer is set to False denoting that the default visualizer should not be run.
  warnings.warn("A media folder path for the MATRX visualizer was "
C:\Users\iuzel\cai_proj\TUD-Collaborative-AI-2023\virt_env\lib\site-packages\matrx\logger\logger.py:57: DeprecationWarning: ActionLogger will be updated in the future towards ActionLoggerV2. Switch to the usage of ActionLoggerV2 to prevent future problems.
  warnings.warn(
C:\Users\iuzel\cai_proj\TUD-Collaborative-AI-2023\virt_env\lib\site-packages\matrx\agents\agent_utils\state_tracker.py:39: PendingDeprecationWarning: The StateTracker will be deprecated in a future version of MATRX, replaced by State.
  warnings.warn(

And this is what localhost:3000 looks like after successful completion of the initial questions asked(task type/name/human condition):
![image](https://user-images.githubusercontent.com/104033987/220798447-f9d802b1-134c-465b-a7c1-669d18dd09ae.png)

None of the buttons function.
It could be because of the fact that `run_matrx_visualizer` is set to False, but since I have not make any modifications on the code, so how can this be the case?

SOLVED: After killing the port and re-connecting, everything seems to be working fine.

**Comment by rsverhagen94** [comment]
Hi @ziyar-uzel. Did you solve the issue in the end, or are you still encountering the problem?

**Comment by ziyar-uzel** [comment]
Hi,
I have solved it. Thank you for asking.
________________________________
